apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: static-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: static-site
        image: ghcr.io/gautamgoel789/static-site:green      # ✅ your locally built image
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: static-site-active
      previewService: static-site-preview
      autoPromotionEnabled: false

