apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: static-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: static-site
        image: gautamgoel789/static-site@sha256:PLACEHOLDER  # Replaced by pipeline
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: static-site-active
      previewService: static-site-preview
      autoPromotionEnabled: false       # ❌ No auto promotion — manual approval required
      previewReplicaCount: 2            # ✅ Keep both blue and green running
